//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAUIMiniApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAUIMiniApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CQ Authenticator.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string Btn_Add_Account {
            get {
                return ResourceManager.GetString("Btn_Add_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Btn_Add_Manual {
            get {
                return ResourceManager.GetString("Btn_Add_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        public static string Btn_Scan_QRCode {
            get {
                return ResourceManager.GetString("Btn_Scan_QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Btn_ToSPage_Accept {
            get {
                return ResourceManager.GetString("Btn_ToSPage_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Btn_ToSPage_Reject {
            get {
                return ResourceManager.GetString("Btn_ToSPage_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account no..
        /// </summary>
        public static string Ent_AcctNo_Placeholder {
            get {
                return ResourceManager.GetString("Ent_AcctNo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company code.
        /// </summary>
        public static string Ent_CompanyCode_Placeholder {
            get {
                return ResourceManager.GetString("Ent_CompanyCode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your key.
        /// </summary>
        public static string Ent_SecretKey_Placeholder {
            get {
                return ResourceManager.GetString("Ent_SecretKey_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields.
        /// </summary>
        public static string Fill_All_Fields {
            get {
                return ResourceManager.GetString("Fill_All_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading_Indicator {
            get {
                return ResourceManager.GetString("Loading_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account failed to add.
        /// </summary>
        public static string New_Account_Add_Failed {
            get {
                return ResourceManager.GetString("New_Account_Add_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account successfully added.
        /// </summary>
        public static string New_Account_Added {
            get {
                return ResourceManager.GetString("New_Account_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account.
        /// </summary>
        public static string New_Account_Title {
            get {
                return ResourceManager.GetString("New_Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scan result to process.
        /// </summary>
        public static string No_QRCode_Result {
            get {
                return ResourceManager.GetString("No_QRCode_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong QR Code format.
        /// </summary>
        public static string Wrong_QRCode_Format {
            get {
                return ResourceManager.GetString("Wrong_QRCode_Format", resourceCulture);
            }
        }
    }
}
